<?php

        include "connexion.php";

        date_default_timezone_set('America/Bogota');
        $fechaHoy = date('Y/m/d');
        $anios =date('Y');
        $mes = date('m');
        $horaHoy = date('H:i:s');
        $minutoHoy = date('i');


        

        function Cuerpo(){
            
            

            // VENTAS NETAS
            $conceptp[] = array ('ID' => 1, 'Concep'=>'ACEITES', 'campo' => 'ACEITES');
            $conceptp[] = array ('ID' => 2, 'Concep'=>'MARGARINAS', 'campo' => 'MARGARINAS' );
            $conceptp[] = array ('ID' => 3, 'Concep'=>'SOLIDOS Y CREMOSOS', 'campo' => 'SOLIDOS_CREMOSOS' );
            $conceptp[] = array ('ID' => 4, 'Concep'=>'<font style="font-weight:bold;">TOTAL PRODUCTO TERMINADO</font>', 'campo' => '(ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)' );
            $conceptp[] = array ('ID' => 5, 'Concep'=>'INDUSTRIALES', 'campo' => 'INDUSTRIALES' );
            $conceptp[] = array ('ID' => 6, 'Concep'=>'OTROS (AGL-ACIDULADO)', 'campo' => 'ACIDOS_GRASOS_ACIDULADO' );
            $conceptp[] = array ('ID' => 7, 'Concep'=>'SERVICIO DE MAQUILA', 'campo' => 'SERVICIO_MAQUILA' );
            $conceptp[] = array ('ID' => 8, 'Concep'=>'<font style="font-weight:bold;">TOTAL OTROS</font>', 'campo' => '(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA)' );
            $conceptp[] = array ('ID' => 9, 'Concep'=>'<font style="font-weight:bold;">TOTAL VENTAS</font>', 'campo' => '((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))' );
            
            
            // COSTOS DE VENTAS
            
            $conceptp[] = array ('ID' => 10, 'Concep'=>'ACEITES', 'campo' => 'ACEITES2');
            $conceptp[] = array ('ID' => 11, 'Concep'=>'PORCENTAJE ACEITES', 'campo' => '((ACEITES2/ACEITES)*100)');
            $conceptp[] = array ('ID' => 12, 'Concep'=>'MARGARINAS', 'campo' => 'MARGARINAS2' );
            $conceptp[] = array ('ID' => 13, 'Concep'=>'PORCENTAJE MARGARINAS', 'campo' => '((MARGARINAS2/MARGARINAS)*100)');
            $conceptp[] = array ('ID' => 14, 'Concep'=>'SOLIDOS Y CREMOSOS', 'campo' => 'SOLIDOS_CREMOSOS2' );
            $conceptp[] = array ('ID' => 15, 'Concep'=>'PORCENTAJE SOLIDOS Y CREMOSOS', 'campo' => '((SOLIDOS_CREMOSOS2/SOLIDOS_CREMOSOS)*100)');
            $conceptp[] = array ('ID' => 16, 'Concep'=>'<font style="font-weight:bold;">TOTAL PRODUCTO TERMINADO</font>', 'campo' => '(ACEITES2+MARGARINAS2+SOLIDOS_CREMOSOS2)' );
            $conceptp[] = array ('ID' => 17, 'Concep'=>'PORCENTAJE TOTAL PRODUCTO TERMINADO', 'campo' => '((ACEITES2+MARGARINAS2+SOLIDOS_CREMOSOS2)/(ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)*100)');
            $conceptp[] = array ('ID' => 18, 'Concep'=>'INDUSTRIALES', 'campo' => 'INDUSTRIALES2' );
            $conceptp[] = array ('ID' => 19, 'Concep'=>'PORCENTAJE INDUSTRIALES', 'campo' => '(INDUSTRIALES2/INDUSTRIALES)*100');
            $conceptp[] = array ('ID' => 20, 'Concep'=>'OTROS PRODUCTOS', 'campo' => 'ACIDOS_GRASOS_ACIDULADO2' );
            $conceptp[] = array ('ID' => 21, 'Concep'=>'PORCENTAJE OTROS PRODUCTOS', 'campo' => '((ACIDOS_GRASOS_ACIDULADO2/ACIDOS_GRASOS_ACIDULADO)*100)');
            $conceptp[] = array ('ID' => 22, 'Concep'=>'SERVICIO DE MAQUILA', 'campo' => 'SERVICIO_MAQUILA2' );
            $conceptp[] = array ('ID' => 23, 'Concep'=>'PORCENTAJE SERVICIO DE MAQUILA', 'campo' => '((SERVICIO_MAQUILA2/SERVICIO_MAQUILA)*100)');
            $conceptp[] = array ('ID' => 24, 'Concep'=>'<font style="font-weight:bold;">TOTAL OTROS</font>', 'campo' => '(INDUSTRIALES2+ACIDOS_GRASOS_ACIDULADO2+SERVICIO_MAQUILA2)' );
            $conceptp[] = array ('ID' => 25, 'Concep'=>'PORCENTAJE TOTAL OTROS', 'campo' => '((INDUSTRIALES2+ACIDOS_GRASOS_ACIDULADO2+SERVICIO_MAQUILA2)/(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA)*100)');
            $conceptp[] = array ('ID' => 26, 'Concep'=>'<font style="font-weight:bold;">TOTAL COSTOS DE VENTAS</font>', 'campo' => '((ACEITES2+MARGARINAS2+SOLIDOS_CREMOSOS2)+(INDUSTRIALES2+SERVICIO_MAQUILA2+SERVICIO_MAQUILA2))' );
            $conceptp[] = array ('ID' => 27, 'Concep'=>'PORCENTAJE TOTAL COSTOS DE VENTAS', 'campo' => '(((ACEITES2+MARGARINAS2+SOLIDOS_CREMOSOS2)+(INDUSTRIALES2+SERVICIO_MAQUILA2+SERVICIO_MAQUILA2))/((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))*100)');
            $conceptp[] = array ('ID' => 28, 'Concep'=>'<font style="font-weight:bold;">UTILIDAD BRUTA</font>', 'campo' => '(((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-((ACEITES2+MARGARINAS2+SOLIDOS_CREMOSOS2)+(INDUSTRIALES2+ACIDOS_GRASOS_ACIDULADO2+SERVICIO_MAQUILA2)))' );
            $conceptp[] = array ('ID' => 29, 'Concep'=>'PORCENTAJE UTILIDAD BRUTA', 'campo' => '((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-((ACEITES2+MARGARINAS2+SOLIDOS_CREMOSOS2)+(INDUSTRIALES2+ACIDOS_GRASOS_ACIDULADO2+SERVICIO_MAQUILA2)))/((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))*100)');

            
            // GASTOS OPERACIONALES
           
            $conceptp[] = array ('ID' => 30, 'Concep'=>'<font style="font-weight:bold;">GASTOS DE ADMINISTRACION</font>', 'campo' => 'GASTOS_ADMINISTRACION');
            $conceptp[] = array ('ID' => 31, 'Concep'=>'PORCENTAJE GASTOS DE ADMINISTRACION', 'campo' => '(GASTOS_ADMINISTRACION/((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))*100)' );
            $conceptp[] = array ('ID' => 32, 'Concep'=>'GATOS DE PERSONAL', 'campo' => 'GASTOS_PERSONAL' );
            $conceptp[] = array ('ID' => 33, 'Concep'=>'PORCENTAJE GATOS DE PERSONAL', 'campo' => '(GASTOS_PERSONAL/((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))*100)' );
            $conceptp[] = array ('ID' => 34, 'Concep'=>'HONORARIOS', 'campo' => 'HONORARIOS' );
            $conceptp[] = array ('ID' => 35, 'Concep'=>'PORCENTAJE HONORARIOS ', 'campo' => '(HONORARIOS/((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))*100/)' );
            $conceptp[] = array ('ID' => 36, 'Concep'=>'SERVICIOS', 'campo' => 'SERVICIOS' );
            $conceptp[] = array ('ID' => 37, 'Concep'=>'PORCENTAJE SERVICIOS ', 'campo' => '(SERVICIOS/((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))*100)' );
            $conceptp[] = array ('ID' => 38, 'Concep'=>'OTROS', 'campo' => '(GASTOS_ADMINISTRACION-GASTOS_PERSONAL-HONORARIOS-SERVICIOS)' );
            $conceptp[] = array ('ID' => 39, 'Concep'=>'PORCENTAJE OTROS', 'campo' => '(OTROS/((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))*100)' );
            $conceptp[] = array ('ID' => 40, 'Concep'=>'<font style="font-weight:bold;">GASTOS DE VENTAS</font>', 'campo' => 'GASTOS_VENTAS' );
            $conceptp[] = array ('ID' => 41, 'Concep'=>'PORCENTAJE GASTOS DE VENTAS', 'campo' => '(GASTOS_VENTAS/((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))*100)' );
            $conceptp[] = array ('ID' => 42, 'Concep'=>'GATOS DE PERSONAL', 'campo' => 'GASTOS_PERSONAL2' );
            $conceptp[] = array ('ID' => 43, 'Concep'=>'PORCENTAJE GATOS DE PERSONAL', 'campo' => '(GASTOS_PERSONAL2/((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))*100)' );
            $conceptp[] = array ('ID' => 44, 'Concep'=>'POLIZA CARTERA', 'campo' => 'POLIZA_CARTERA');
            $conceptp[] = array ('ID' => 45, 'Concep'=>'PORCENTAJE POLIZA CARTERA', 'campo' => '(POLIZA_CARTERA/((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))*100)' );
            $conceptp[] = array ('ID' => 46, 'Concep'=>'FLETES', 'campo' => 'FLETES');
            $conceptp[] = array ('ID' => 47, 'Concep'=>'PORCENTAJE FLETES', 'campo' => '(FLETES/((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))*100)' );
            $conceptp[] = array ('ID' => 48, 'Concep'=>'SERVICIO LOGISTICO', 'campo' => 'SERVICIO_LOGISTICO' );
            $conceptp[] = array ('ID' => 49, 'Concep'=>'PORCENTAJE SERVICIO LOGISTICO', 'campo' => '(SERVICIO_LOGISTICO/((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))*100)' );
            $conceptp[] = array ('ID' => 50, 'Concep'=>'ESTRATEGIA COMERCIAL', 'campo' => 'ESTRATEGIA_COMERCIAL' );
            $conceptp[] = array ('ID' => 51, 'Concep'=>'PORCENTAJE ESTRATEGIA COMERCIAL', 'campo' => '(ESTRATEGIA_COMERCIAL/((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))*100)' );
            $conceptp[] = array ('ID' => 52, 'Concep'=>'IMPUESTOS', 'campo' => 'IMPUESTOS' );
            $conceptp[] = array ('ID' => 53, 'Concep'=>'PORCENTAJE IMPUESTOS', 'campo' => '(IMPUESTOS/((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))*100)' );
            $conceptp[] = array ('ID' => 54, 'Concep'=>'DESCUENTOS PRONTO PAGO', 'campo' => 'DES_PRONTO_PAGO' );
            $conceptp[] = array ('ID' => 55, 'Concep'=>'PORCENTAJE DESCUENTOS PRONTO PAGO', 'campo' => '(DES_PRONTO_PAGO/((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))*100)' );
            $conceptp[] = array ('ID' => 56, 'Concep'=>'OTROS', 'campo' => '(GASTOS_VENTAS-GASTOS_PERSONAL2-POLIZA_CARTERA-FLETES-SERVICIO_LOGISTICO-ESTRATEGIA_COMERCIAL-IMPUESTOS-DES_PRONTO_PAGO)' );
            $conceptp[] = array ('ID' => 57, 'Concep'=>'PORCENTAJE OTROS', 'campo' => '((GASTOS_VENTAS-GASTOS_PERSONAL2-POLIZA_CARTERA-FLETES-SERVICIO_LOGISTICO-ESTRATEGIA_COMERCIAL-IMPUESTOS-DES_PRONTO_PAGO)/((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))*100)' );
            $conceptp[] = array ('ID' => 58, 'Concep'=>'<font style="font-weight:bold;">DEPRECIACIONES Y AMORTIZACIONES</font>', 'campo' => 'DEPRECIACIONES_AMORTIZACIONES' );
            $conceptp[] = array ('ID' => 59, 'Concep'=>'PORCENTAJE DEPRECIACIONES Y AMORTIZACIONES', 'campo' => '(DEPRECIACIONES_AMORTIZACIONES/((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))*100)' );
            $conceptp[] = array ('ID' => 60, 'Concep'=>'<font style="font-weight:bold;"> TOTAL GASTOS OPERACIONALES</font>', 'campo' => '(GASTOS_ADMINISTRACION+GASTOS_VENTAS+DEPRECIACIONES_AMORTIZACIONES)' );
            $conceptp[] = array ('ID' => 61, 'Concep'=>'PORCENTAJE TOTAL GASTOS OPERACIONALES', 'campo' => '((GASTOS_ADMINISTRACION+GASTOS_VENTAS+DEPRECIACIONES_AMORTIZACIONES)/((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))*100)' );
            $conceptp[] = array ('ID' => 62, 'Concep'=>'<font style="font-weight:bold;">UTILIDAD OPERACIONAL</font>', 'campo' => '(((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-((ACEITES2+MARGARINAS2+SOLIDOS_CREMOSOS2)+(INDUSTRIALES2+ACIDOS_GRASOS_ACIDULADO2+SERVICIO_MAQUILA2))-((GASTOS_ADMINISTRACION+GASTOS_VENTAS+DEPRECIACIONES_AMORTIZACIONES)))' );
            $conceptp[] = array ('ID' => 63, 'Concep'=>'PORCENTAJE UTILIDAD OPERACIONAL', 'campo' => '((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-((ACEITES2+MARGARINAS2+SOLIDOS_CREMOSOS2)+(INDUSTRIALES2+ACIDOS_GRASOS_ACIDULADO2+SERVICIO_MAQUILA2))-((GASTOS_ADMINISTRACION+GASTOS_VENTAS+DEPRECIACIONES_AMORTIZACIONES)))/((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))*100)' );

            
            // GASTOS NO OPERACIONALES
           
            $conceptp[] = array ('ID' => 64 , 'Concep'=>'FINANCIEROS', 'campo'=>'FINANCIEROS');
            $conceptp[] = array ('ID' => 65 , 'Concep'=>'PORCENTAJE FINANCIEROS', 'campo'=>'(FINANCIEROS/((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))*100)');
            $conceptp[] = array ('ID' => 66 , 'Concep'=>'RETIRO DE ACTIVOS (LEASE BACK - AJUSTE INVENTARIOS)', 'campo'=>'RETIRO_ACTIVOS');
            $conceptp[] = array ('ID' => 67 , 'Concep'=>'PORCENTAJE RETIRO DE ACTIVOS', 'campo'=>'(RETIRO_ACTIVOS/((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))*100)');
            $conceptp[] = array ('ID' => 68 , 'Concep'=>'GRAVAMEN MOVIMIENTO FINANCIERO (4*1000)', 'campo'=>'GRAVA_MOV_FINANCIERO');
            $conceptp[] = array ('ID' => 69 , 'Concep'=>'PORCENTAJE GRAVAMEN MOVIMIENTO', 'campo'=>'(GRAVA_MOV_FINANCIERO/((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))*100)');
            $conceptp[] = array ('ID' => 70 , 'Concep'=>'OTROS', 'campo'=>'(OTROS-FINANCIEROS-RETIRO_ACTIVOS-GRAVA_MOV_FINANCIERO)');
            $conceptp[] = array ('ID' => 71 , 'Concep'=>'PORCENTAJE OTROS', 'campo'=>'((OTROS-FINANCIEROS-RETIRO_ACTIVOS-GRAVA_MOV_FINANCIERO)/((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))*100)');
            $conceptp[] = array ('ID' => 72 , 'Concep'=>'<font style="font-weight:bold;">TOTAL NO  OPERACIONALES</font>', 'campo'=>'((FINANCIEROS+RETIRO_ACTIVOS+GRAVA_MOV_FINANCIERO)+(OTROS-FINANCIEROS-RETIRO_ACTIVOS-GRAVA_MOV_FINANCIERO))');
            $conceptp[] = array ('ID' => 73 , 'Concep'=>'PORCENTAJE TOTAL NO  OPERACIONALES', 'campo'=>'(((FINANCIEROS+RETIRO_ACTIVOS+GRAVA_MOV_FINANCIERO)+(OTROS-FINANCIEROS-RETIRO_ACTIVOS-GRAVA_MOV_FINANCIERO))/((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))*100)');
            $conceptp[] = array ('ID' => 74 , 'Concep'=>'<font style="font-weight:bold;">UTILIDAD ANTES DE IMPUESTOS</font>', 'campo'=>'((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-((ACEITES2+MARGARINAS2+SOLIDOS_CREMOSOS2)+(INDUSTRIALES2+ACIDOS_GRASOS_ACIDULADO2+SERVICIO_MAQUILA2))-((GASTOS_ADMINISTRACION+GASTOS_VENTAS+DEPRECIACIONES_AMORTIZACIONES)))-(((FINANCIEROS+RETIRO_ACTIVOS+GRAVA_MOV_FINANCIERO)+(OTROS-FINANCIEROS-RETIRO_ACTIVOS-GRAVA_MOV_FINANCIERO))))');
            $conceptp[] = array ('ID' => 75 , 'Concep'=>'PORCENTAJE UTILIDAD ANTES DE IMPUESTOS', 'campo'=>'(((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-((ACEITES2+MARGARINAS2+SOLIDOS_CREMOSOS2)+(INDUSTRIALES2+ACIDOS_GRASOS_ACIDULADO2+SERVICIO_MAQUILA2))-((GASTOS_ADMINISTRACION+GASTOS_VENTAS+DEPRECIACIONES_AMORTIZACIONES)))-(((FINANCIEROS+RETIRO_ACTIVOS+GRAVA_MOV_FINANCIERO)+(OTROS-FINANCIEROS-RETIRO_ACTIVOS-GRAVA_MOV_FINANCIERO))))/((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))*100)');
            $conceptp[] = array ('ID' => 76 , 'Concep'=>'<font style="font-weight:bold;">EBITDA</font>', 'campo'=>'(((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-((ACEITES2+MARGARINAS2+SOLIDOS_CREMOSOS2)+(INDUSTRIALES2+ACIDOS_GRASOS_ACIDULADO2+SERVICIO_MAQUILA2))-((GASTOS_ADMINISTRACION+GASTOS_VENTAS+DEPRECIACIONES_AMORTIZACIONES)))-(((FINANCIEROS+RETIRO_ACTIVOS+GRAVA_MOV_FINANCIERO)+(OTROS-FINANCIEROS-RETIRO_ACTIVOS-GRAVA_MOV_FINANCIERO))))+((FINANCIEROS+RETIRO_ACTIVOS+GRAVA_MOV_FINANCIERO)+(OTROS-FINANCIEROS-RETIRO_ACTIVOS-GRAVA_MOV_FINANCIERO))+(DEPRECIACIONES_AMORTIZACIONES+EBITDA))');
            $conceptp[] = array ('ID' => 77 , 'Concep'=>'PORCENTAJE EBITDA', 'campo'=>'((((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-((ACEITES2+MARGARINAS2+SOLIDOS_CREMOSOS2)+(INDUSTRIALES2+ACIDOS_GRASOS_ACIDULADO2+SERVICIO_MAQUILA2))-((GASTOS_ADMINISTRACION+GASTOS_VENTAS+DEPRECIACIONES_AMORTIZACIONES)))-(((FINANCIEROS+RETIRO_ACTIVOS+GRAVA_MOV_FINANCIERO)+(OTROS-FINANCIEROS-RETIRO_ACTIVOS-GRAVA_MOV_FINANCIERO))))+((FINANCIEROS+RETIRO_ACTIVOS+GRAVA_MOV_FINANCIERO)+(OTROS-FINANCIEROS-RETIRO_ACTIVOS-GRAVA_MOV_FINANCIERO))+(DEPRECIACIONES_AMORTIZACIONES+EBITDA))/((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))*100)');
             
            
            // VENTAS TONELADAS PRECIO UNITARIO

            $conceptp[] = array('ID' => 78, 'Concep'=>'<font style="font-weight:bold;">VENTAS (TONELADAS)</font>', 'campo'=>'(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO)');
            $conceptp[] = array('ID' => 79, 'Concep'=>'ACEITES TONELADAS', 'campo'=>'TON_ACEITES');
            $conceptp[] = array('ID' => 80, 'Concep'=>'MARGARINAS TONELADAS', 'campo'=>'TON_MARGARINAS');
            $conceptp[] = array('ID' => 81, 'Concep'=>'SOLIDOS Y CREMOSOS TONELADAS', 'campo'=>'TON_SOLIDOS_CREMOSOS');
            $conceptp[] = array('ID' => 82, 'Concep'=>'<font style="font-weight:bold;">TOTAL PT</font>', 'campo'=>'(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS)');
            $conceptp[] = array('ID' => 83, 'Concep'=>'INDUSTRIALES (OLEOQUIMICOS)', 'campo'=>'TON_INDUSTRIALES_OLEO');
            $conceptp[] = array('ID' => 84, 'Concep'=>'OTROS (AGL-ACIDULADO)', 'campo'=>'TON_ACIDOS_GRASOS_ACIDULADO');
            $conceptp[] = array('ID' => 85, 'Concep'=>'<font style="font-weight:bold;">SERVICIO MAQUILA</font>', 'campo'=>'TON_SERVICIO_MAQUILA');

            
            // VENTAS NETAS PRECIO UNITARIO
            
            $conceptp[] = array ('ID' => 86, 'Concep'=>'ACEITES', 'campo' => '(ACEITES/TON_ACEITES)');
            $conceptp[] = array ('ID' => 87, 'Concep'=>'MARGARINAS', 'campo' => '(MARGARINAS/TON_MARGARINAS)' );
            $conceptp[] = array ('ID' => 88, 'Concep'=>'SOLIDOS Y CREMOSOS', 'campo' => '(SOLIDOS_CREMOSOS/TON_SOLIDOS_CREMOSOS)' );
            $conceptp[] = array ('ID' => 89, 'Concep'=>'<font style="font-weight:bold;">TOTAL PRODUCTO TERMINADO</font>', 'campo' => '((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS))' );
            $conceptp[] = array ('ID' => 90, 'Concep'=>'INDUSTRIALES', 'campo' => '(INDUSTRIALES/TON_INDUSTRIALES_OLEO)' );
            $conceptp[] = array ('ID' => 91, 'Concep'=>'OTROS (AGL-ACIDULADO)', 'campo' => '(ACIDOS_GRASOS_ACIDULADO/TON_ACIDOS_GRASOS_ACIDULADO)' );
            $conceptp[] = array ('ID' => 92, 'Concep'=>'SERVICIO DE MAQUILA', 'campo' => '(SERVICIO_MAQUILA/TON_SERVICIO_MAQUILA)' );
            //$conceptp[] = array ('ID' => 93, 'Concep'=>'<font style="font-weight:bold;">TOTAL OTROS</font>', 'campo' => '' );
            $conceptp[] = array ('ID' => 94, 'Concep'=>'<font style="font-weight:bold;">TOTAL VENTAS</font>', 'campo' => '((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-(SERVICIO_MAQUILA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))' );
           

            // COSTOS DE VENTAS PRECIO UNITARIO
            
            $conceptp[] = array ('ID' => 95, 'Concep'=>'ACEITES', 'campo' => '(ACEITES2/TON_ACEITES)');
            $conceptp[] = array ('ID' => 96, 'Concep'=>'PORCENTAJE ACEITES', 'campo' => '(((ACEITES2/TON_ACEITES)/(ACEITES/TON_ACEITES))*100)');
            $conceptp[] = array ('ID' => 97, 'Concep'=>'MARGARINAS', 'campo' => '(MARGARINAS2/TON_MARGARINAS)');
            $conceptp[] = array ('ID' => 98, 'Concep'=>'PORCENTAJE MARGARINAS', 'campo' => '(((MARGARINAS2/TON_MARGARINAS)/(MARGARINAS/TON_MARGARINAS))*100)');
            $conceptp[] = array ('ID' => 99, 'Concep'=>'SOLIDOS Y CREMOSOS', 'campo' => '(SOLIDOS_CREMOSOS2/TON_SOLIDOS_CREMOSOS)' );
            $conceptp[] = array ('ID' => 100, 'Concep'=>'PORCENTAJE SOLIDOS Y CREMOSOS', 'campo' => '(((SOLIDOS_CREMOSOS2/TON_SOLIDOS_CREMOSOS)/(SOLIDOS_CREMOSOS/TON_SOLIDOS_CREMOSOS))*100)');
            $conceptp[] = array ('ID' => 101, 'Concep'=>'INDUSTRIALES', 'campo' => '(INDUSTRIALES2/TON_INDUSTRIALES_OLEO)' );
            $conceptp[] = array ('ID' => 102, 'Concep'=>'PORCENTAJE INDUSTRIALES', 'campo' => '(((INDUSTRIALES2/TON_INDUSTRIALES_OLEO)/(INDUSTRIALES/TON_INDUSTRIALES_OLEO))*100)');
            $conceptp[] = array ('ID' => 103, 'Concep'=>'OTROS PRODUCTOS', 'campo' => '(ACIDOS_GRASOS_ACIDULADO2/TON_ACIDOS_GRASOS_ACIDULADO)' );
            $conceptp[] = array ('ID' => 104, 'Concep'=>'PORCENTAJE OTROS PRODUCTOS', 'campo' => '(((ACIDOS_GRASOS_ACIDULADO2/TON_ACIDOS_GRASOS_ACIDULADO)/(ACIDOS_GRASOS_ACIDULADO/TON_ACIDOS_GRASOS_ACIDULADO))*100)');
            $conceptp[] = array ('ID' => 105, 'Concep'=>'SERVICIO DE MAQUILA', 'campo' => '(SERVICIO_MAQUILA2/TON_SERVICIO_MAQUILA)' );
            $conceptp[] = array ('ID' => 106, 'Concep'=>'PORCENTAJE SERVICIO DE MAQUILA', 'campo' => '(((SERVICIO_MAQUILA2/TON_SERVICIO_MAQUILA)/(SERVICIO_MAQUILA/TON_SERVICIO_MAQUILA))*100)');
            $conceptp[] = array ('ID' => 107, 'Concep'=>'<font style="font-weight:bold;">TOTAL COSTOS DE VENTAS</font>', 'campo' => '(((ACEITES2+MARGARINAS2+SOLIDOS_CREMOSOS2)+(INDUSTRIALES2+SERVICIO_MAQUILA2+SERVICIO_MAQUILA2))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))' );
            $conceptp[] = array ('ID' => 108, 'Concep'=>'PORCENTAJE TOTAL COSTOS DE VENTAS', 'campo' => '((((ACEITES2+MARGARINAS2+SOLIDOS_CREMOSOS2)+(INDUSTRIALES2+SERVICIO_MAQUILA2+SERVICIO_MAQUILA2))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))/((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-(SERVICIO_MAQUILA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))*100)');
            $conceptp[] = array ('ID' => 109, 'Concep'=>'<font style="font-weight:bold;">UTILIDAD BRUTA</font>', 'campo' => '(((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-(SERVICIO_MAQUILA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))-(((ACEITES2+MARGARINAS2+SOLIDOS_CREMOSOS2)+(INDUSTRIALES2+SERVICIO_MAQUILA2+SERVICIO_MAQUILA2))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO)))' );
            $conceptp[] = array ('ID' => 110, 'Concep'=>'PORCENTAJE UTILIDAD BRUTA', 'campo' => '((((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-(SERVICIO_MAQUILA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))-(((ACEITES2+MARGARINAS2+SOLIDOS_CREMOSOS2)+(INDUSTRIALES2+SERVICIO_MAQUILA2+SERVICIO_MAQUILA2))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO)))/((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-(SERVICIO_MAQUILA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))*100)');

            
            //GASTOS OPERACIONALES PRECIO UNITARIO

            $conceptp[] = array ('ID' => 111 , 'Concep'=>'<font style="font-weight:bold;">GASTOS DE ADMINISTRACION</font>', 'campo' => '(GASTOS_ADMINISTRACION/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))');
            $conceptp[] = array ('ID' => 112 , 'Concep'=>'PORCENTAJE GASTOS DE ADMINISTRACION', 'campo' => '((GASTOS_ADMINISTRACION/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))/((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-(SERVICIO_MAQUILA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))*100)' );
            $conceptp[] = array ('ID' => 113 , 'Concep'=>'GATOS DE PERSONAL', 'campo' => '(GASTOS_PERSONAL/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))' );
            $conceptp[] = array ('ID' => 114 , 'Concep'=>'PORCENTAJE GATOS DE PERSONAL', 'campo' => '((GASTOS_PERSONAL/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))/((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-(SERVICIO_MAQUILA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))*100)' );
            $conceptp[] = array ('ID' => 115 , 'Concep'=>'HONORARIOS', 'campo' => '(HONORARIOS/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))' );
            $conceptp[] = array ('ID' => 116 , 'Concep'=>'PORCENTAJE HONORARIOS ', 'campo' => '((HONORARIOS/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))/((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-(SERVICIO_MAQUILA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))*100)' );
            $conceptp[] = array ('ID' => 117 , 'Concep'=>'SERVICIOS', 'campo' => '(SERVICIOS/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))' );
            $conceptp[] = array ('ID' => 118 , 'Concep'=>'PORCENTAJE SERVICIOS ', 'campo' => '((SERVICIOS/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))/((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-(SERVICIO_MAQUILA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))*100)' );
            $conceptp[] = array ('ID' => 119 , 'Concep'=>'OTROS', 'campo' => '((GASTOS_ADMINISTRACION-GASTOS_PERSONAL-HONORARIOS-SERVICIOS)/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))' );
            $conceptp[] = array ('ID' => 120 , 'Concep'=>'PORCENTAJE OTROS', 'campo' => '(((GASTOS_ADMINISTRACION-GASTOS_PERSONAL-HONORARIOS-SERVICIOS)/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))/((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-(SERVICIO_MAQUILA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))*100)' );
            $conceptp[] = array ('ID' => 121 , 'Concep'=>'<font style="font-weight:bold;">GASTOS DE VENTAS</font>', 'campo' => '(GASTOS_VENTAS/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))' );
            $conceptp[] = array ('ID' => 122 , 'Concep'=>'PORCENTAJE GASTOS DE VENTAS', 'campo' => '((GASTOS_VENTAS/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))/((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-(SERVICIO_MAQUILA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))*100)' );
            $conceptp[] = array ('ID' => 123 , 'Concep'=>'GATOS DE PERSONAL', 'campo' => '(GASTOS_PERSONAL2/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))' );
            $conceptp[] = array ('ID' => 124 , 'Concep'=>'PORCENTAJE GATOS DE PERSONAL', 'campo' => '((GASTOS_PERSONAL2/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))/((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-(SERVICIO_MAQUILA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))*100)' );
            $conceptp[] = array ('ID' => 125 , 'Concep'=>'POLIZA CARTERA', 'campo' => '(POLIZA_CARTERA/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))');
            $conceptp[] = array ('ID' => 126 , 'Concep'=>'PORCENTAJE POLIZA CARTERA', 'campo' => '((POLIZA_CARTERA/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))/((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-(SERVICIO_MAQUILA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))*100)' );
            $conceptp[] = array ('ID' => 127 , 'Concep'=>'FLETES', 'campo' => '(FLETES/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))');
            $conceptp[] = array ('ID' => 128 , 'Concep'=>'PORCENTAJE FLETES', 'campo' => '((FLETES/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))/((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-(SERVICIO_MAQUILA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))*100)' );
            $conceptp[] = array ('ID' => 129 , 'Concep'=>'SERVICIO LOGISTICO', 'campo' => '(SERVICIO_LOGISTICO/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))' );
            $conceptp[] = array ('ID' => 130 , 'Concep'=>'PORCENTAJE SERVICIO LOGISTICO', 'campo' => '((SERVICIO_LOGISTICO/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))/((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-(SERVICIO_MAQUILA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))*100)' );
            $conceptp[] = array ('ID' => 131 , 'Concep'=>'ESTRATEGIA COMERCIAL', 'campo' => '(ESTRATEGIA_COMERCIAL/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))' );
            $conceptp[] = array ('ID' => 132 , 'Concep'=>'PORCENTAJE ESTRATEGIA COMERCIAL', 'campo' => '((ESTRATEGIA_COMERCIAL/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))/((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-(SERVICIO_MAQUILA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))*100)' );
            $conceptp[] = array ('ID' => 133 , 'Concep'=>'IMPUESTOS', 'campo' => '(IMPUESTOS/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))' );
            $conceptp[] = array ('ID' => 134 , 'Concep'=>'PORCENTAJE IMPUESTOS', 'campo' => '((IMPUESTOS/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))/((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-(SERVICIO_MAQUILA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))*100)' );
            $conceptp[] = array ('ID' => 135 , 'Concep'=>'DESCUENTOS PRONTO PAGO', 'campo' => '(DES_PRONTO_PAGO/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))' );
            $conceptp[] = array ('ID' => 136 , 'Concep'=>'PORCENTAJE DESCUENTOS PRONTO PAGO', 'campo' => '((DES_PRONTO_PAGO/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))/((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-(SERVICIO_MAQUILA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))*100)' );
            $conceptp[] = array ('ID' => 137 , 'Concep'=>'OTROS', 'campo' => '((GASTOS_VENTAS-GASTOS_PERSONAL2-POLIZA_CARTERA-FLETES-SERVICIO_LOGISTICO-ESTRATEGIA_COMERCIAL-IMPUESTOS-DES_PRONTO_PAGO)/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))' );
            $conceptp[] = array ('ID' => 138 , 'Concep'=>'PORCENTAJE OTROS', 'campo' => '(((GASTOS_VENTAS-GASTOS_PERSONAL2-POLIZA_CARTERA-FLETES-SERVICIO_LOGISTICO-ESTRATEGIA_COMERCIAL-IMPUESTOS-DES_PRONTO_PAGO)/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))/((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-(SERVICIO_MAQUILA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))*100)' );
            $conceptp[] = array ('ID' => 139 , 'Concep'=>'<font style="font-weight:bold;">DEPRECIACIONES Y AMORTIZACIONES</font>', 'campo' => '(DEPRECIACIONES_AMORTIZACIONES/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))' );
            $conceptp[] = array ('ID' => 140 , 'Concep'=>'PORCENTAJE DEPRECIACIONES Y AMORTIZACIONES', 'campo' => '((DEPRECIACIONES_AMORTIZACIONES/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))/((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-(SERVICIO_MAQUILA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))*100)' );
            $conceptp[] = array ('ID' => 141 , 'Concep'=>'<font style="font-weight:bold;"> TOTAL GASTOS OPERACIONALES</font>', 'campo' => '((GASTOS_ADMINISTRACION/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))+(GASTOS_VENTAS/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))+(DEPRECIACIONES_AMORTIZACIONES/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO)))' );
            $conceptp[] = array ('ID' => 142 , 'Concep'=>'PORCENTAJE TOTAL GASTOS OPERACIONALES', 'campo' => '(((GASTOS_ADMINISTRACION/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))+(GASTOS_VENTAS/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))+(DEPRECIACIONES_AMORTIZACIONES/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO)))/((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-(SERVICIO_MAQUILA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))*100)' );
            $conceptp[] = array ('ID' => 143 , 'Concep'=>'<font style="font-weight:bold;">UTILIDAD OPERACIONAL</font>', 'campo' => '((((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-(SERVICIO_MAQUILA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))-(((ACEITES2+MARGARINAS2+SOLIDOS_CREMOSOS2)+(INDUSTRIALES2+SERVICIO_MAQUILA2+SERVICIO_MAQUILA2))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO)))-((GASTOS_ADMINISTRACION/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))+(GASTOS_VENTAS/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))+(DEPRECIACIONES_AMORTIZACIONES/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))))' );
            $conceptp[] = array ('ID' => 144 , 'Concep'=>'PORCENTAJE UTILIDAD OPERACIONAL', 'campo' => '(((((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-(SERVICIO_MAQUILA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))-(((ACEITES2+MARGARINAS2+SOLIDOS_CREMOSOS2)+(INDUSTRIALES2+SERVICIO_MAQUILA2+SERVICIO_MAQUILA2))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO)))-((GASTOS_ADMINISTRACION/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))+(GASTOS_VENTAS/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))+(DEPRECIACIONES_AMORTIZACIONES/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))))/((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-(SERVICIO_MAQUILA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))*100)' );
            
            
            // GASTOS NO OPERACIONALES PRECIO UNITARIO

            $conceptp[] = array ('ID' => 145 , 'Concep'=>'FINANCIEROS', 'campo'=>'(FINANCIEROS/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))');
            $conceptp[] = array ('ID' => 146 , 'Concep'=>'PORCENTAJE FINANCIEROS', 'campo'=>'((FINANCIEROS/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))/((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-(SERVICIO_MAQUILA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))*100)');
            $conceptp[] = array ('ID' => 147 , 'Concep'=>'RETIRO DE ACTIVOS (LEASE BACK - AJUSTE INVENTARIOS)', 'campo'=>'(RETIRO_ACTIVOS/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))');
            $conceptp[] = array ('ID' => 148 , 'Concep'=>'PORCENTAJE RETIRO DE ACTIVOS', 'campo'=>'((RETIRO_ACTIVOS/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))/((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-(SERVICIO_MAQUILA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))*100)');
            $conceptp[] = array ('ID' => 149 , 'Concep'=>'GRAVAMEN MOVIMIENTO FINANCIERO (4*1000)', 'campo'=>'(GRAVA_MOV_FINANCIERO/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))');
            $conceptp[] = array ('ID' => 150 , 'Concep'=>'PORCENTAJE GRAVAMEN MOVIMIENTO', 'campo'=>'((GRAVA_MOV_FINANCIERO/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))/((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-(SERVICIO_MAQUILA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))*100)');
            $conceptp[] = array ('ID' => 151 , 'Concep'=>'OTROS', 'campo'=>'((OTROS-FINANCIEROS-RETIRO_ACTIVOS-GRAVA_MOV_FINANCIERO)/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))');
            $conceptp[] = array ('ID' => 152 , 'Concep'=>'PORCENTAJE OTROS', 'campo'=>'(((OTROS-FINANCIEROS-RETIRO_ACTIVOS-GRAVA_MOV_FINANCIERO)/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))/((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-(SERVICIO_MAQUILA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))*100)');
            $conceptp[] = array ('ID' => 153 , 'Concep'=>'<font style="font-weight:bold;">TOTAL NO  OPERACIONALES</font>', 'campo'=>'((FINANCIEROS/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))+(RETIRO_ACTIVOS/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))+(GRAVA_MOV_FINANCIERO/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))+((OTROS-FINANCIEROS-RETIRO_ACTIVOS-GRAVA_MOV_FINANCIERO)/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO)))');
            $conceptp[] = array ('ID' => 154 , 'Concep'=>'PORCENTAJE TOTAL NO  OPERACIONALES', 'campo'=>'(((FINANCIEROS/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))+(RETIRO_ACTIVOS/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))+(GRAVA_MOV_FINANCIERO/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))+((OTROS-FINANCIEROS-RETIRO_ACTIVOS-GRAVA_MOV_FINANCIERO)/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO)))/((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-(SERVICIO_MAQUILA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))*100)');
            $conceptp[] = array ('ID' => 155 , 'Concep'=>'<font style="font-weight:bold;">UTILIDAD ANTES DE IMPUESTOS</font>', 'campo'=>'(((((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-(SERVICIO_MAQUILA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))-(((ACEITES2+MARGARINAS2+SOLIDOS_CREMOSOS2)+(INDUSTRIALES2+SERVICIO_MAQUILA2+SERVICIO_MAQUILA2))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO)))-((GASTOS_ADMINISTRACION/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))+(GASTOS_VENTAS/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))+(DEPRECIACIONES_AMORTIZACIONES/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))))-((FINANCIEROS/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))+(RETIRO_ACTIVOS/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))+(GRAVA_MOV_FINANCIERO/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))+((OTROS-FINANCIEROS-RETIRO_ACTIVOS-GRAVA_MOV_FINANCIERO)/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))))');
            $conceptp[] = array ('ID' => 156 , 'Concep'=>'PORCENTAJE UTILIDAD ANTES DE IMPUESTOS', 'campo'=>'((((((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-(SERVICIO_MAQUILA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))-(((ACEITES2+MARGARINAS2+SOLIDOS_CREMOSOS2)+(INDUSTRIALES2+SERVICIO_MAQUILA2+SERVICIO_MAQUILA2))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO)))-((GASTOS_ADMINISTRACION/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))+(GASTOS_VENTAS/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))+(DEPRECIACIONES_AMORTIZACIONES/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))))-((FINANCIEROS/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))+(RETIRO_ACTIVOS/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))+(GRAVA_MOV_FINANCIERO/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))+((OTROS-FINANCIEROS-RETIRO_ACTIVOS-GRAVA_MOV_FINANCIERO)/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))))/((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-(SERVICIO_MAQUILA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))*100)');
            $conceptp[] = array ('ID' => 157 , 'Concep'=>'<font style="font-weight:bold;">EBITDA</font>', 'campo'=>'((((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-((ACEITES2+MARGARINAS2+SOLIDOS_CREMOSOS2)+(INDUSTRIALES2+ACIDOS_GRASOS_ACIDULADO2+SERVICIO_MAQUILA2))-((GASTOS_ADMINISTRACION+GASTOS_VENTAS+DEPRECIACIONES_AMORTIZACIONES)))-(((FINANCIEROS+RETIRO_ACTIVOS+GRAVA_MOV_FINANCIERO)+(OTROS-FINANCIEROS-RETIRO_ACTIVOS-GRAVA_MOV_FINANCIERO))))+((FINANCIEROS+RETIRO_ACTIVOS+GRAVA_MOV_FINANCIERO)+(OTROS-FINANCIEROS-RETIRO_ACTIVOS-GRAVA_MOV_FINANCIERO))+(DEPRECIACIONES_AMORTIZACIONES+EBITDA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))');
            $conceptp[] = array ('ID' => 158 , 'Concep'=>'PORCENTAJE EBITDA', 'campo'=>'(((((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-((ACEITES2+MARGARINAS2+SOLIDOS_CREMOSOS2)+(INDUSTRIALES2+ACIDOS_GRASOS_ACIDULADO2+SERVICIO_MAQUILA2))-((GASTOS_ADMINISTRACION+GASTOS_VENTAS+DEPRECIACIONES_AMORTIZACIONES)))-(((FINANCIEROS+RETIRO_ACTIVOS+GRAVA_MOV_FINANCIERO)+(OTROS-FINANCIEROS-RETIRO_ACTIVOS-GRAVA_MOV_FINANCIERO))))+((FINANCIEROS+RETIRO_ACTIVOS+GRAVA_MOV_FINANCIERO)+(OTROS-FINANCIEROS-RETIRO_ACTIVOS-GRAVA_MOV_FINANCIERO))+(DEPRECIACIONES_AMORTIZACIONES+EBITDA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))/((((ACEITES+MARGARINAS+SOLIDOS_CREMOSOS)+(INDUSTRIALES+ACIDOS_GRASOS_ACIDULADO+SERVICIO_MAQUILA))-(SERVICIO_MAQUILA))/(TON_ACEITES+TON_MARGARINAS+TON_SOLIDOS_CREMOSOS+TON_INDUSTRIALES_OLEO+TON_ACIDOS_GRASOS_ACIDULADO))*100)');
            
            return $conceptp;


        }
      
        
    	function RangoFecha($inicio, $final){

            

            $FechaIni=strtotime($inicio);	
            $FechaFin=strtotime($final);   
            
            for($i=$FechaFin; $i>=$FechaIni; $i-=86400){
                $ListaAnio[] = array('Anio' => date("Y", $i), 'CODMES' => date("m", $i));
            }
     
            $ListAnio[] = array();
            //print_r($ListaAnio);
    
            foreach($ListaAnio as $t) {
                $repeat=false;	
                    for($i=0;$i<count($ListAnio);$i++){
                        if( $ListAnio[$i]['Anio']==$t['Anio'] AND $ListAnio[$i]['CODMES']==$t['CODMES']){
                            $ListAnio[$i]['Anio'];
                            $ListAnio[$i]['CODMES'];
                            //print_r($ListaAnio);
                            $repeat=true; 
                        break;
                        } 
                        
                    }
                    
                                 
                if($repeat==false)
                    $ListAnio[] = array('Anio' => $t['Anio'], 'CODMES' => $t['CODMES']);
            }

    
            array_shift($ListAnio);

            $arregloOrdenado = array_reverse($ListAnio);
           
            
            foreach($arregloOrdenado as $Tri){
                
                $fechaI = $Tri['Anio'].'-'.$Tri['CODMES'].'-01';

                $fechaF = $Tri['Anio'].'-'.$Tri['CODMES'].'-01';

                $trimestre[]= array('FechaI' => $fechaI, 'FechaF'=> $fechaF);

                if(count($trimestre)==1 or count($trimestre)==5 or count($trimestre)==9 or count($trimestre)==13 or count($trimestre)==17 or count($trimestre)==21 or count($trimestre)==25 or count($trimestre)==29 or count($trimestre)==33){


                    $PosI = $fechaI;


                }

                if(count($trimestre)==3 or count($trimestre)==7 or count($trimestre)==11 or count($trimestre)==15 or count($trimestre)==19 or count($trimestre)==23 or count($trimestre)==27 or count($trimestre)==31 or count($trimestre)==35){

                    $trimestre[]= array('FechaI' => $PosI, 'FechaF'=> $fechaF);
                    

                }
                
                    
            }
                        
            return $trimestre;
           

    
        }

        
        
         function NombreMeses($Mes){
            $Meses[] = array('Mes' => 1, 'NombMes' => 'ENERO');
            $Meses[] = array('Mes' => 2, 'NombMes' => 'FEBRERO');
            $Meses[] = array('Mes' => 3, 'NombMes' => 'MARZO');
            $Meses[] = array('Mes' => 4, 'NombMes' => 'ABRIL');
            $Meses[] = array('Mes' => 5, 'NombMes' => 'MAYO');
            $Meses[] = array('Mes' => 6, 'NombMes' => 'JUNIO');
            $Meses[] = array('Mes' => 7, 'NombMes' => 'JULIO');
            $Meses[] = array('Mes' => 8, 'NombMes' => 'AGOSTO');
            $Meses[] = array('Mes' => 9, 'NombMes' => 'SEPTIEMBRE');
            $Meses[] = array('Mes'=> 10, 'NombMes' => 'OCTUBRE');
            $Meses[] = array('Mes'=> 11, 'NombMes' => 'NOVIEMBRE');
            $Meses[] = array('Mes'=> 12, 'NombMes' => 'DICIEMBRE');
    
            return $NombreMes = $Meses[$Mes-1]['NombMes'];
    
        }

         function Meses(){
            $Meses[] = array('Mes' => 1, 'NombMes' => 'ENERO');
            $Meses[] = array('Mes' => 2, 'NombMes' => 'FEBRERO');
            $Meses[] = array('Mes' => 3, 'NombMes' => 'MARZO');
            $Meses[] = array('Mes' => 4, 'NombMes' => 'ABRIL');
            $Meses[] = array('Mes' => 5, 'NombMes' => 'MAYO');
            $Meses[] = array('Mes' => 6, 'NombMes' => 'JUNIO');
            $Meses[] = array('Mes' => 7, 'NombMes' => 'JULIO');
            $Meses[] = array('Mes' => 8, 'NombMes' => 'AGOSTO');
            $Meses[] = array('Mes' => 9, 'NombMes' => 'SEPTIEMBRE');
            $Meses[] = array('Mes'=> 10, 'NombMes' => 'OCTUBRE');
            $Meses[] = array('Mes'=> 11, 'NombMes' => 'NOVIEMBRE');
            $Meses[] = array('Mes'=> 12, 'NombMes' => 'DICIEMBRE');
    
            return $Meses;
    
        }

        


?>